### ISSUE TITLE
Change landing page

### ISSUE THREAD

**Issue by dpeekstok** [bbjdt2224/SSC#1]
When you open a web browser that is pointing at the project's root, you will see the default Laravel home page. You can change this by editing which view is returned on the '/' route or add a redirect from '/' to another page, such as login. E.g.

`Route::get('/', function () {
    return redirect('login');
});`

**Comment by bbjdt2224** [comment]
I changed it to a new page would it be better to send the to login or leave the welcome screen

**Comment by dpeekstok** [comment]
Since there isn't any functionality for non-users, its perfectly acceptable to just forward them to the login page. We have quite a few pages that do that, including the success center website.

**Comment by bbjdt2224** [comment]
what about people registering for the first time?

**Comment by dpeekstok** [comment]
On the Login page, there is a link to the register page so new users can sign up. Its up to you if you want to keep the welcome page or just have a redirect to login. Either one works.
