### ISSUE TITLE
Error on creating a user

### ISSUE THREAD

**Issue by dpeekstok** [bbjdt2224/SSC#2]
When a new user is registering, you receive an error when MySQL tries to create the user. You should either have LoginController add a value for hours or create a default value in the migration. 

![screen shot 2017-10-20 at 1 30 14 pm](https://user-images.githubusercontent.com/10521217/31834031-867bf65a-b59a-11e7-9ce3-da8347c71ee0.png)

**Comment by bbjdt2224** [comment]
i changed the default
