### ISSUE TITLE
Error when creating first timesheet for new users

### ISSUE THREAD

**Issue by dpeekstok** [bbjdt2224/SSC#3]
When you create a new timesheet for the first time, it comes up with an error message. Since I'm a new user, I don't have any timesheets yet, so userinfo would be null. It looks like you are trying to assign a value to an object that doesn't exist. 

![screen shot 2017-10-20 at 3 03 51 pm](https://user-images.githubusercontent.com/10521217/31837641-9b4b4326-b5a7-11e7-8de6-f5f1d4f17b45.png)

**Comment by bbjdt2224** [comment]
I use a empty time sheet in the timesheets table where the user is equal to -1
i didn't want to make a new time sheet just in case the user didn't mean to click the new time sheet button

**Comment by bbjdt2224** [comment]
i added a folder called tables with a sql file inside with the blank time sheet for creating a new time sheet

**Comment by dpeekstok** [comment]
You shouldn't use raw sql files for adding default table values. [Use seeds instead.](https://laravel.com/docs/5.5/seeding)

**Comment by bbjdt2224** [comment]
i was using somthing like a seed i just didnt know what it was called or that laravel made one for you

**Comment by dpeekstok** [comment]
I have found the issue. You load your main js file at the end of app.blade.php, instead of in the header. This line `<script src="{{ asset('js/app.js') }}"></script>` **MUST** be in the html header. If you are ever including external js files, you must have them loaded before anything else so that they are available to other any js in your webpage.

**Comment by dpeekstok** [comment]
Your seed works. I no longer get any errors when creating new timesheets.
