### ISSUE TITLE
Fix Routes

### ISSUE THREAD

**Issue by dpeekstok** [bbjdt2224/SSC#4]
All anchor tags, sources, and actions should use proper urls generated from php. This will help us a lot when we go to launch the website so that routing works better. If you define static routes, they will usually only work on your own machine. Instead, if you let laravel create the route for you, it will work on all platforms. Many of your routes are done correctly, but here is a list of some of the ones that I've noticed that are done with the regular method.

Proper routes should look like `<a href="{{route('select')}}">Select</a>` or `<script src="{{asset('js/totals.js')}}"></script>`

Example bad urls:

home.blade.php
`<a href="../select" class='btn btn-danger'>Back</a>`
`<script src="../js/totals.js"></script>`

sign.blade.php
`<script src="../js/signature.js"></script>`

layouts/app.blade.php
`<a href="/laravel/ssc/public/index.php/records">Records</a>`
`<a href="/laravel/ssc/public/index.php/admin">Current</a>`

admin.blade.php
`<a href="prevusers" class="btn btn-primary">Past Employees</a>`
`<a href="timesheet/{{$user[0]->id}}">`
`<a href="admin/change/{{$user[0]->id}}" class="btn btn-primary">Change</a>`
`<a href="remove/{{$user[0]->id}}" class='btn btn-danger'>Remove</button>`

changehours.blade.php
`<form action="../../admin" method="post">`
  
pastusers.blade.php
`<td><a href="addUser/{{$person->id}}" class="btn btn-default">Un-Remove</a></td>`

search.blade.php
`<form method='POST' action='search'>`

select.blade.php
`<a href="new" class="btn btn-primary">New Timesheet</a>`
`<a href="home/{{$timesheet->startdate}}" class='btn btn-default'>`

welcome.blade.php
`<img src="step.png">`

**Comment by bbjdt2224** [comment]
when i try to use the {{ route('select') }} way it gives me a route undefined error

**Comment by dpeekstok** [comment]
If the route is named (E.g. `Route::get('/home', 'HomeController@index')->name('home');`) you want to use route('home'), otherwise use `url('/home')`.
