### ISSUE TITLE
Signature doesn't have a default value

### ISSUE THREAD

**Issue by dpeekstok** [bbjdt2224/SSC#8]
Can't make new timesheets. Signature doesn't have a default value so it breaks. You should allow it to be null in your migration. 

![screen shot 2017-10-25 at 10 53 41 am](https://user-images.githubusercontent.com/10521217/32005646-cd4d1600-b972-11e7-8e9b-a708d6904b2b.png)

**Comment by bbjdt2224** [comment]
i made the signature nullable that should fix the issue
