### ISSUE TITLE
Can't view old timesheets

### ISSUE THREAD

**Issue by dpeekstok** [bbjdt2224/SSC#9]
I think we talked about this at the first meeting we had, but there isn't a way to view old timesheets. As an employee, I can see all of my timesheets that I've submitted.  

![screen shot 2017-10-25 at 11 02 28 am](https://user-images.githubusercontent.com/10521217/32006202-157c2f1e-b974-11e7-8aab-0fd74b9b9488.png)

However, the admin can only see the most recent timesheet for each employee. There isn't a way for the admin to view the previous timesheet. 

![screen shot 2017-10-25 at 11 02 22 am](https://user-images.githubusercontent.com/10521217/32006276-554949ec-b974-11e7-80af-57871837cc59.png)

You could have a date range at the top of both pages that will allow users and admins to see all timesheets that are in that date range. If i'm a tutor for the success center for 2 years, I'll have over 50 timesheets that I've submitted. I won't always want to see all of those. 

Either that or allow the admin's search to see the timesheets that were submitted for that pay period. Currently, it only shows that one was submitted. 

Finally, when you do the search, you should search for timesheets that would have that day on it. For example, if I click on the 10th, it doesn't show any timesheets, but there was a timesheet that started on the 9th that has hours scheduled on the 10th. An easy way to do this would be to to a [whereBetween](https://laravel.com/docs/5.5/queries#where-clauses) on your timesheet search and give the selected day and 13 days before that day. That will always return the timesheet for that week.

**Comment by bbjdt2224** [comment]
while logged in as the admin if you click on the admin drop down in the navbar there is an option to view records which are old timesheets

**Comment by dpeekstok** [comment]
You can see that something was submitted but you can't see what it is or click on it. 
![screen shot 2017-10-25 at 1 31 40 pm](https://user-images.githubusercontent.com/10521217/32013354-da251222-b988-11e7-96b1-febdd842b84a.png)
